# Generated by Django 5.2.17 on 2026-10-01 08:05

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ownership', '0002_postgresql_ownership_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AuthDenial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='AccountContact',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('activated_at', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('email__endswith', '@example.invalid'), ('email', django.db.models.functions.text.Lower('email'))), name='account_synthetic_email_only')],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_digest', models.CharField(editable=False, max_length=64)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('used_at', models.DateTimeField(editable=False, null=True)),
                ('revoked_at', models.DateTimeField(editable=False, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ownership.membership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('used_at__isnull', True)), fields=('membership',), name='invitation_one_pending'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='invitation_positive_lifetime'), models.CheckConstraint(condition=models.Q(('used_at__isnull', True), ('revoked_at__isnull', True), _connector='OR'), name='invitation_one_terminal_state')],
            },
        ),
    ]
