# Generated by Django 5.2.17 on 2026-10-01 11:55

import account_security.crypto
import django.db.models.deletion
import django.utils.timezone
import django_otp.util
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ownership', '0002_postgresql_ownership_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSecurity',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('recovery_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Authenticator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The human-readable name of this device.', max_length=64)),
                ('confirmed', models.BooleanField(default=True, help_text='Is this device ready for use?')),
                ('throttling_failure_timestamp', models.DateTimeField(blank=True, default=None, help_text='A timestamp of the last failed verification attempt. Null if last attempt succeeded.', null=True)),
                ('throttling_failure_count', models.PositiveIntegerField(default=0, help_text='Number of successive failed attempts.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this device was initially created in the system.', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='The most recent date and time this device was used.', null=True)),
                ('key', account_security.crypto.EncryptedTextField(default=django_otp.util.random_hex)),
                ('step', models.PositiveSmallIntegerField(default=30)),
                ('t0', models.BigIntegerField(default=0)),
                ('digits', models.PositiveSmallIntegerField(default=6)),
                ('tolerance', models.PositiveSmallIntegerField(default=1)),
                ('drift', models.SmallIntegerField(default=0)),
                ('last_t', models.BigIntegerField(default=-1)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('enrollment_hash', models.CharField(blank=True, max_length=64)),
                ('enrollment_version', models.PositiveBigIntegerField(default=1)),
                ('expires_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_hash', models.CharField(max_length=64, unique=True)),
                ('credential_hash', models.CharField(max_length=64)),
                ('version', models.PositiveBigIntegerField()),
                ('level', models.CharField(choices=[('full', 'Full'), ('enroll', 'Enroll'), ('recover', 'Recover')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(null=True)),
                ('password_confirmed_at', models.DateTimeField(null=True)),
                ('factor_confirmed_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('authenticator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account_security.authenticator')),
            ],
        ),
        migrations.CreateModel(
            name='ExportPermit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ownership.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_security.accountsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveBigIntegerField()),
                ('credential_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verifier', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryPermit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('version', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kind', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('credential_hash', models.CharField(max_length=64)),
                ('version', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('authenticator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account_security.authenticator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accountsession',
            name='trusted_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account_security.trusteddevice'),
        ),
        migrations.AddConstraint(
            model_name='authenticator',
            constraint=models.UniqueConstraint(condition=models.Q(('confirmed', True), ('revoked_at__isnull', True)), fields=('user',), name='security_one_active_totp'),
        ),
    ]
