# Generated by Django 5.2.17 on 2026-10-07 11:15

import django.db.models.deletion
from django.db import migrations, models
from decimal import Decimal
from access_control import financial_migration_operations as preserved
from access_control.financial_guards import install, uninstall


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_access_guards'),
        ('ownership', '0002_postgresql_ownership_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheticFinance',
            fields=[
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='access_control.syntheticrecord')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        preserved.RemoveConstraint(
            model_name='grant',
            name='access_known_operation',
        ),
        preserved.AddField(
            model_name='exportbinding',
            name='finance_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_exports', to='access_control.grant'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='resource',
            field=models.CharField(choices=[('memberships', 'Memberships'), ('synthetic_record', 'Record'), ('synthetic_finance', 'Finance')], max_length=24),
        ),
        preserved.AddConstraint(
            model_name='grant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action__in', ['view', 'manage_access']), ('cabinet__isnull', True), ('resource', 'memberships')), models.Q(('action__in', ['view', 'export', 'change', 'manage_access']), ('resource', 'synthetic_record')), models.Q(('action__in', ['view', 'export', 'change', 'manage_access']), ('platform__isnull', True), ('resource', 'synthetic_finance')), _connector='OR'), name='access_known_operation'),
        ),
        preserved.AddField(
            model_name='syntheticfinance',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ownership.cabinet'),
        ),
        preserved.AddField(
            model_name='syntheticfinance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ownership.organization'),
        ),
        preserved.AddConstraint(
            model_name='syntheticfinance',
            constraint=models.CheckConstraint(condition=models.Q(('revenue__gte', 0), ('revenue__lte', Decimal('999999999999.99'))), name='finance_revenue_range'),
        ),
        preserved.AddConstraint(
            model_name='syntheticfinance',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0), ('cost__lte', Decimal('999999999999.99'))), name='finance_cost_range'),
        ),
        preserved.AddConstraint(
            model_name='syntheticfinance',
            constraint=models.CheckConstraint(condition=models.Q(('expenses__gte', 0), ('expenses__lte', Decimal('999999999999.99'))), name='finance_expenses_range'),
        ),
        preserved.AddConstraint(
            model_name='syntheticfinance',
            constraint=models.CheckConstraint(condition=models.Q(('payout__gte', 0), ('payout__lte', Decimal('999999999999.99'))), name='finance_payout_range'),
        ),
        migrations.RunPython(install, uninstall),
    ]
