# Generated by Django 5.2.17 on 2026-09-30 14:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('marketplace', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ownership.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CabinetLegalEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('observed_from', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('observed_until', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_entity_history', to='ownership.cabinet')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ownership.legalentity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ownership.organization')),
            ],
        ),
        migrations.AddField(
            model_name='cabinet',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ownership.organization'),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ownership.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('source_type', models.CharField(max_length=80)),
                ('seller_identity', models.CharField(max_length=200)),
                ('secret_reference', models.CharField(blank=True, max_length=200)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ownership.cabinet')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ownership.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('observer', 'Observer'), ('cabinet_user', 'Cabinet user')], max_length=20)),
                ('state', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ownership.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='membership_user_org_unique'), models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'observer', 'cabinet_user'])), name='membership_role_valid'), models.CheckConstraint(condition=models.Q(('state__in', ['active', 'suspended'])), name='membership_state_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='legalentity',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='legal_org_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='cabinetlegalentity',
            constraint=models.UniqueConstraint(condition=models.Q(('observed_until__isnull', True)), fields=('cabinet',), name='cabinet_one_current_legal'),
        ),
        migrations.AddConstraint(
            model_name='cabinetlegalentity',
            constraint=models.CheckConstraint(condition=models.Q(('observed_until__isnull', True), ('observed_until__gt', models.F('observed_from')), _connector='OR'), name='cabinet_legal_positive_interval'),
        ),
        migrations.AddConstraint(
            model_name='cabinet',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='cabinet_org_id_unique'),
        ),
    ]
